# See the documentation for more information:
# https://packit.dev/docs/configuration/

# the insights-proxy RPM specfile.
specfile_path: insights-proxy.spec

upstream_project_url: https://github.com/abellotti/insights-proxy-service

jobs:
  - job: copr_build
    trigger: pull_request
    targets: &targets_list
      # we officially support rhel-9 downstream.
      - rhel-9-x86_64
      - rhel-9-aarch64

  - job: copr_build
    trigger: commit
    branch: main
    owner: abellott
    project: "insights-proxy-service-latest"
    preserve_project: True
    targets: *targets_list

