# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rhproxy.spec

upstream_project_url: https://github.com/RedHatInsights/rhproxy

jobs:
  - job: copr_build
    trigger: pull_request
    targets: &targets_list
      # we officially support rhel-9 downstream
      - rhel-9-x86_64
      - rhel-9-aarch64
      # and latest fedora releases
      - fedora-39-x86_64
      - fedora-39-aarch64
      - fedora-40-x86_64
      - fedora-40-aarch64

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@rhproxy"
    project: "rhproxy-latest"
    preserve_project: True
    targets: *targets_list

  - job: copr_build
    trigger: release
    owner: "@rhproxy"
    project: "rhproxy"
    preserve_project: True
    targets: *targets_list

