name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "feature/*"]

jobs:
  check-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: pip3 install pyquery

      - name: Check dependencies
        run: |
          make check-epel-servers
